[package]
name = "beverage"
description = "Hypothetical Editor for Bevy. Also available as a t-shirt."
version = "0.1.0"
repository = "https://github.com/knutsoned/beverage"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/pcwalton/bevy.git", branch = "brp", version = "0.14.0-dev" }
